# Generated by Django 3.1.3 on 2023-02-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_branch_user_ifsc_alter_user_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.IntegerField(blank=True, default=514670),
        ),
    ]
