# Generated by Django 3.1.3 on 2023-02-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tpp',
            fields=[
                ('T_id', models.AutoField(primary_key=True, serialize=False)),
                ('T_name', models.CharField(max_length=100)),
                ('T_bankName', models.CharField(max_length=100)),
                ('T_accountNo', models.IntegerField(default=0)),
                ('T_ifsc', models.CharField(max_length=100)),
                ('T_branch', models.CharField(max_length=100)),
            ],
        ),
    ]
