# Generated by Django 3.1.3 on 2020-12-03 13:11

import datetime
from django.db import migrations, models
import django.utils.timezone 


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
